#add ,remove ,stack ,split -> how to do these operations on elements of an arrays


#we have to a create a new array because array has fixed size

**for insert array : syntax -> np.insert(array,index_no,value,axis = None)
array - original array , Index - position_no where we want to insert an array .
value : actual data
axis : none (insert into flatter )
for 2d  = 0( rows wise data  insertion )
1 for column wise **

In [1]:
import numpy as np
arr = np.array([10,20,30,40,50,60,70])
new_arr = np.insert(arr,2,100,axis = 0)
print(new_arr)#by default  - row wise

[ 10  20 100  30  40  50  60  70]


**Insert in 2 D**

In [4]:
arr_2d = np.array([[1,2],[3,4]])
#insert a new row at index 1
new_arr_2d = np.insert(arr_2d,1,[5,6],axis = None)
print(new_arr_2d)
#

[1 5 6 2 3 4]


**Append: if we want to add an element at the end**

In [5]:
arr = np.array([1,2,3,4,5])
new_arr = np.append(arr,6)
print(new_arr)

[1 2 3 4 5 6]


**To concatenate two arrays or joining two array**

In [8]:
#np.concatenate(arr1,arr2,axis = 0) axis 0 - vertical stacking , axis 1 - Horizontal stacking
arr_1 = np.array([1,2,3,4,5])
arr_2 = np.array([6,7,8,9,10])

new_arr = np.concatenate((arr_1,arr_2),axis = 0)
print(new_arr)




[ 1  2  3  4  5  6  7  8  9 10]


**Removing elements  of array**

In [9]:
#delete function : np.delete(array, index,axis = None)
#Flattern array
arr = np.array([10,20,30,40,50])
new_arr = np.delete(arr,2,axis = 0)
print(new_arr)

[10 20 40 50]


**For 2D**

In [11]:
arr_2d = np.array([[1,2,3],[4,5,6]])
new_arr_2d = np.delete(arr_2d,1,axis = 0)
print(new_arr_2d)

[[1 2 3]]


**stacking  and splitting**

*vertically : vstack() - row wise*
*Horizontally : hstack( ) column wise*

In [14]:
arr1 = np.array([1,5,7])
arr2 = np.array([2,4,6])
new_arr = np.vstack((arr1,arr2))
print(new_arr)


[[1 5 7]
 [2 4 6]]


In [15]:
arr1 = np.array([1,5,7])
arr2 = np.array([5,8,7])
new_arr = np.hstack((arr1,arr2))
print(new_arr)

[1 5 7 5 8 7]


**Splitting**

*np.split() for equal*
*np.hsplit()*
*np.vsplit()*

In [17]:
arr = np.array([5,9,10,10,12,13])
new_arr = np.split(arr,2)
print(new_arr)

#if split size not matched -> will give value error

[array([ 5,  9, 10]), array([10, 12, 13])]


In [21]:
arr = np.array([[1,5,3],[7,8,9]])
new_arr = np.vsplit(arr, 2)
print(new_arr)

[array([[1, 5, 3]]), array([[7, 8, 9]])]


**Day 05 : Broadcasting and Vectorization**

*Broadcasting :  perform mathematical operations in array (easy by broadcasting)*

Without Broadcasting (10% discount) mathematical operation

In [25]:
prices = [100,200,300] #slow
discount = 10 #10 % discount
final_prices = []
for price in prices:
  final_prices.append(price - price*discount/100)
print(final_prices)

[90.0, 180.0, 270.0]


**Broadcasting is a numpy way where we do different mathematical operations - direct apply without using loops**

In [26]:
#fast and easy
#by using broadcasting
prices = np.array([100,200,300])
discount = 10#scalar single value
final_prices = prices - (prices*discount/100)
print(final_prices)

[ 90. 180. 270.]


**How numpy handles arrays of different -different shapes**
*Matching dimension [1,2,3]+[1,2,3]= [2,4,6]*
*Expanding Single elements  [1,2,3] +10 = [11,12,13]*
*Incompatible shapes (if shapes doesn't match) not expanded numpy will give error [1,2,3]+[5,6] will give error*

In [30]:
arr = np.array((100,200,300))
result = (arr * 2)
print(result)

[200 400 600]


**1D TO 2D Broadcasting**

In [32]:
matrix = np.array([[1,2,3],[4,5,6]])
#2 x 3 matrix
vector = np.array([10,20,30]) #1 d array
#1 x 3 matrix
result = matrix + vector
print(result)




[[11 22 33]
 [14 25 36]]


**Incompatable : give error**

In [37]:
arr1 = np.array([[2,5,6],[4,5,6]])

#shape (2,3)
arr2 = np.array([10,20])
#shape (3,)
result = arr1 + arr2
print(result)

#solution of this .reshape()

ValueError: operands could not be broadcast together with shapes (2,3) (2,) 

**Vectorization : on entire array do a operation without using loops** *it

*Without Vectorization*


In [38]:
#using list comprehension
list1 = [1,2,3] #slow
list2 = [4,4,6]
result = [x+y for x,y in zip(list1,list2)]
print(result)

[5, 6, 9]


*Fast Vectorize approach*

In [39]:
arr1 = np.array([1,2,3]) #fast
arr2 = np.array([4,4,6])
result = arr1 + arr2
print(result)

[5 6 9]


In [40]:
arr = np.array([10,20,30])
multiplied  = arr*3
print(multiplied)
#use in AI, Deep Learning

[30 60 90]


broading Expand small array to larger to match
faster than loops

vectorization : work on entire array
100 times faster than loops

scalar broadcasting : we can apply single value on entire elements
and no need of manually repeatation

1d to 2d broadcasting : we can expand 1d to 2d array to complete operation

vectorization
: use in matrix operations

